/**
 * Arco Design Vue 图标名清单（构建期生成，运行时纯字符串，不打包 SVG）。
 * 渲染依赖宿主 app.use(ArcoVueIcon) 已全局注册的 icon-* 组件。
 *
 * 共 287 个图标。
 * - PascalCase：组件名，用于 <component :is="name">
 * - kebab-case：标签名，如 'icon-dashboard'，用于数据库存储 / 菜单 meta.icon
 */

export const arcoIconNames: { pascal: string; kebab: string }[] = [
  { pascal: 'IconAlignCenter', kebab: 'icon-align-center' },
  { pascal: 'IconAlignLeft', kebab: 'icon-align-left' },
  { pascal: 'IconAlignRight', kebab: 'icon-align-right' },
  { pascal: 'IconAlipayCircle', kebab: 'icon-alipay-circle' },
  { pascal: 'IconApps', kebab: 'icon-apps' },
  { pascal: 'IconArchive', kebab: 'icon-archive' },
  { pascal: 'IconArrowDown', kebab: 'icon-arrow-down' },
  { pascal: 'IconArrowFall', kebab: 'icon-arrow-fall' },
  { pascal: 'IconArrowLeft', kebab: 'icon-arrow-left' },
  { pascal: 'IconArrowRight', kebab: 'icon-arrow-right' },
  { pascal: 'IconArrowRise', kebab: 'icon-arrow-rise' },
  { pascal: 'IconArrowUp', kebab: 'icon-arrow-up' },
  { pascal: 'IconAt', kebab: 'icon-at' },
  { pascal: 'IconAttachment', kebab: 'icon-attachment' },
  { pascal: 'IconBackward', kebab: 'icon-backward' },
  { pascal: 'IconBarChart', kebab: 'icon-bar-chart' },
  { pascal: 'IconBgColors', kebab: 'icon-bg-colors' },
  { pascal: 'IconBold', kebab: 'icon-bold' },
  { pascal: 'IconBook', kebab: 'icon-book' },
  { pascal: 'IconBookmark', kebab: 'icon-bookmark' },
  { pascal: 'IconBranch', kebab: 'icon-branch' },
  { pascal: 'IconBrush', kebab: 'icon-brush' },
  { pascal: 'IconBug', kebab: 'icon-bug' },
  { pascal: 'IconBulb', kebab: 'icon-bulb' },
  { pascal: 'IconBytedanceColor', kebab: 'icon-bytedance-color' },
  { pascal: 'IconCalendar', kebab: 'icon-calendar' },
  { pascal: 'IconCalendarClock', kebab: 'icon-calendar-clock' },
  { pascal: 'IconCamera', kebab: 'icon-camera' },
  { pascal: 'IconCaretDown', kebab: 'icon-caret-down' },
  { pascal: 'IconCaretLeft', kebab: 'icon-caret-left' },
  { pascal: 'IconCaretRight', kebab: 'icon-caret-right' },
  { pascal: 'IconCaretUp', kebab: 'icon-caret-up' },
  { pascal: 'IconCheck', kebab: 'icon-check' },
  { pascal: 'IconCheckCircle', kebab: 'icon-check-circle' },
  { pascal: 'IconCheckCircleFill', kebab: 'icon-check-circle-fill' },
  { pascal: 'IconCheckSquare', kebab: 'icon-check-square' },
  { pascal: 'IconChineseFill', kebab: 'icon-chinese-fill' },
  { pascal: 'IconClockCircle', kebab: 'icon-clock-circle' },
  { pascal: 'IconClose', kebab: 'icon-close' },
  { pascal: 'IconCloseCircle', kebab: 'icon-close-circle' },
  { pascal: 'IconCloseCircleFill', kebab: 'icon-close-circle-fill' },
  { pascal: 'IconCloud', kebab: 'icon-cloud' },
  { pascal: 'IconCloudDownload', kebab: 'icon-cloud-download' },
  { pascal: 'IconCode', kebab: 'icon-code' },
  { pascal: 'IconCodeBlock', kebab: 'icon-code-block' },
  { pascal: 'IconCodeSandbox', kebab: 'icon-code-sandbox' },
  { pascal: 'IconCodeSquare', kebab: 'icon-code-square' },
  { pascal: 'IconCodepen', kebab: 'icon-codepen' },
  { pascal: 'IconCommand', kebab: 'icon-command' },
  { pascal: 'IconCommon', kebab: 'icon-common' },
  { pascal: 'IconCompass', kebab: 'icon-compass' },
  { pascal: 'IconComputer', kebab: 'icon-computer' },
  { pascal: 'IconCopy', kebab: 'icon-copy' },
  { pascal: 'IconCopyright', kebab: 'icon-copyright' },
  { pascal: 'IconCustomerService', kebab: 'icon-customer-service' },
  { pascal: 'IconDashboard', kebab: 'icon-dashboard' },
  { pascal: 'IconDelete', kebab: 'icon-delete' },
  { pascal: 'IconDesktop', kebab: 'icon-desktop' },
  { pascal: 'IconDice', kebab: 'icon-dice' },
  { pascal: 'IconDoubleDown', kebab: 'icon-double-down' },
  { pascal: 'IconDoubleLeft', kebab: 'icon-double-left' },
  { pascal: 'IconDoubleRight', kebab: 'icon-double-right' },
  { pascal: 'IconDoubleUp', kebab: 'icon-double-up' },
  { pascal: 'IconDown', kebab: 'icon-down' },
  { pascal: 'IconDownCircle', kebab: 'icon-down-circle' },
  { pascal: 'IconDownload', kebab: 'icon-download' },
  { pascal: 'IconDragArrow', kebab: 'icon-drag-arrow' },
  { pascal: 'IconDragDot', kebab: 'icon-drag-dot' },
  { pascal: 'IconDragDotVertical', kebab: 'icon-drag-dot-vertical' },
  { pascal: 'IconDriveFile', kebab: 'icon-drive-file' },
  { pascal: 'IconEar', kebab: 'icon-ear' },
  { pascal: 'IconEdit', kebab: 'icon-edit' },
  { pascal: 'IconEmail', kebab: 'icon-email' },
  { pascal: 'IconEmpty', kebab: 'icon-empty' },
  { pascal: 'IconEnglishFill', kebab: 'icon-english-fill' },
  { pascal: 'IconEraser', kebab: 'icon-eraser' },
  { pascal: 'IconExclamation', kebab: 'icon-exclamation' },
  { pascal: 'IconExclamationCircle', kebab: 'icon-exclamation-circle' },
  { pascal: 'IconExclamationCircleFill', kebab: 'icon-exclamation-circle-fill' },
  { pascal: 'IconExclamationPolygonFill', kebab: 'icon-exclamation-polygon-fill' },
  { pascal: 'IconExpand', kebab: 'icon-expand' },
  { pascal: 'IconExperiment', kebab: 'icon-experiment' },
  { pascal: 'IconExport', kebab: 'icon-export' },
  { pascal: 'IconEye', kebab: 'icon-eye' },
  { pascal: 'IconEyeInvisible', kebab: 'icon-eye-invisible' },
  { pascal: 'IconFaceBookCircleFill', kebab: 'icon-face-book-circle-fill' },
  { pascal: 'IconFaceFrownFill', kebab: 'icon-face-frown-fill' },
  { pascal: 'IconFaceMehFill', kebab: 'icon-face-meh-fill' },
  { pascal: 'IconFaceSmileFill', kebab: 'icon-face-smile-fill' },
  { pascal: 'IconFacebook', kebab: 'icon-facebook' },
  { pascal: 'IconFacebookSquareFill', kebab: 'icon-facebook-square-fill' },
  { pascal: 'IconFile', kebab: 'icon-file' },
  { pascal: 'IconFileAudio', kebab: 'icon-file-audio' },
  { pascal: 'IconFileImage', kebab: 'icon-file-image' },
  { pascal: 'IconFilePdf', kebab: 'icon-file-pdf' },
  { pascal: 'IconFileVideo', kebab: 'icon-file-video' },
  { pascal: 'IconFilter', kebab: 'icon-filter' },
  { pascal: 'IconFindReplace', kebab: 'icon-find-replace' },
  { pascal: 'IconFire', kebab: 'icon-fire' },
  { pascal: 'IconFolder', kebab: 'icon-folder' },
  { pascal: 'IconFolderAdd', kebab: 'icon-folder-add' },
  { pascal: 'IconFolderDelete', kebab: 'icon-folder-delete' },
  { pascal: 'IconFontColors', kebab: 'icon-font-colors' },
  { pascal: 'IconFormula', kebab: 'icon-formula' },
  { pascal: 'IconForward', kebab: 'icon-forward' },
  { pascal: 'IconFullscreen', kebab: 'icon-fullscreen' },
  { pascal: 'IconFullscreenExit', kebab: 'icon-fullscreen-exit' },
  { pascal: 'IconGift', kebab: 'icon-gift' },
  { pascal: 'IconGithub', kebab: 'icon-github' },
  { pascal: 'IconGitlab', kebab: 'icon-gitlab' },
  { pascal: 'IconGoogle', kebab: 'icon-google' },
  { pascal: 'IconGoogleCircleFill', kebab: 'icon-google-circle-fill' },
  { pascal: 'IconH1', kebab: 'icon-h1' },
  { pascal: 'IconH2', kebab: 'icon-h2' },
  { pascal: 'IconH3', kebab: 'icon-h3' },
  { pascal: 'IconH4', kebab: 'icon-h4' },
  { pascal: 'IconH5', kebab: 'icon-h5' },
  { pascal: 'IconH6', kebab: 'icon-h6' },
  { pascal: 'IconH7', kebab: 'icon-h7' },
  { pascal: 'IconHeart', kebab: 'icon-heart' },
  { pascal: 'IconHeartFill', kebab: 'icon-heart-fill' },
  { pascal: 'IconHighlight', kebab: 'icon-highlight' },
  { pascal: 'IconHistory', kebab: 'icon-history' },
  { pascal: 'IconHome', kebab: 'icon-home' },
  { pascal: 'IconIdcard', kebab: 'icon-idcard' },
  { pascal: 'IconImage', kebab: 'icon-image' },
  { pascal: 'IconImageClose', kebab: 'icon-image-close' },
  { pascal: 'IconImport', kebab: 'icon-import' },
  { pascal: 'IconInfo', kebab: 'icon-info' },
  { pascal: 'IconInfoCircle', kebab: 'icon-info-circle' },
  { pascal: 'IconInfoCircleFill', kebab: 'icon-info-circle-fill' },
  { pascal: 'IconInteraction', kebab: 'icon-interaction' },
  { pascal: 'IconItalic', kebab: 'icon-italic' },
  { pascal: 'IconLanguage', kebab: 'icon-language' },
  { pascal: 'IconLarkColor', kebab: 'icon-lark-color' },
  { pascal: 'IconLaunch', kebab: 'icon-launch' },
  { pascal: 'IconLayers', kebab: 'icon-layers' },
  { pascal: 'IconLayout', kebab: 'icon-layout' },
  { pascal: 'IconLeft', kebab: 'icon-left' },
  { pascal: 'IconLeftCircle', kebab: 'icon-left-circle' },
  { pascal: 'IconLineHeight', kebab: 'icon-line-height' },
  { pascal: 'IconLink', kebab: 'icon-link' },
  { pascal: 'IconList', kebab: 'icon-list' },
  { pascal: 'IconLiveBroadcast', kebab: 'icon-live-broadcast' },
  { pascal: 'IconLoading', kebab: 'icon-loading' },
  { pascal: 'IconLocation', kebab: 'icon-location' },
  { pascal: 'IconLock', kebab: 'icon-lock' },
  { pascal: 'IconLoop', kebab: 'icon-loop' },
  { pascal: 'IconMan', kebab: 'icon-man' },
  { pascal: 'IconMenu', kebab: 'icon-menu' },
  { pascal: 'IconMenuFold', kebab: 'icon-menu-fold' },
  { pascal: 'IconMenuUnfold', kebab: 'icon-menu-unfold' },
  { pascal: 'IconMessage', kebab: 'icon-message' },
  { pascal: 'IconMessageBanned', kebab: 'icon-message-banned' },
  { pascal: 'IconMindMapping', kebab: 'icon-mind-mapping' },
  { pascal: 'IconMinus', kebab: 'icon-minus' },
  { pascal: 'IconMinusCircle', kebab: 'icon-minus-circle' },
  { pascal: 'IconMinusCircleFill', kebab: 'icon-minus-circle-fill' },
  { pascal: 'IconMobile', kebab: 'icon-mobile' },
  { pascal: 'IconMoon', kebab: 'icon-moon' },
  { pascal: 'IconMoonFill', kebab: 'icon-moon-fill' },
  { pascal: 'IconMore', kebab: 'icon-more' },
  { pascal: 'IconMoreVertical', kebab: 'icon-more-vertical' },
  { pascal: 'IconMosaic', kebab: 'icon-mosaic' },
  { pascal: 'IconMusic', kebab: 'icon-music' },
  { pascal: 'IconMute', kebab: 'icon-mute' },
  { pascal: 'IconMuteFill', kebab: 'icon-mute-fill' },
  { pascal: 'IconNav', kebab: 'icon-nav' },
  { pascal: 'IconNotification', kebab: 'icon-notification' },
  { pascal: 'IconNotificationClose', kebab: 'icon-notification-close' },
  { pascal: 'IconObliqueLine', kebab: 'icon-oblique-line' },
  { pascal: 'IconOrderedList', kebab: 'icon-ordered-list' },
  { pascal: 'IconOriginalSize', kebab: 'icon-original-size' },
  { pascal: 'IconPalette', kebab: 'icon-palette' },
  { pascal: 'IconPaste', kebab: 'icon-paste' },
  { pascal: 'IconPause', kebab: 'icon-pause' },
  { pascal: 'IconPauseCircle', kebab: 'icon-pause-circle' },
  { pascal: 'IconPauseCircleFill', kebab: 'icon-pause-circle-fill' },
  { pascal: 'IconPen', kebab: 'icon-pen' },
  { pascal: 'IconPenFill', kebab: 'icon-pen-fill' },
  { pascal: 'IconPhone', kebab: 'icon-phone' },
  { pascal: 'IconPlayArrow', kebab: 'icon-play-arrow' },
  { pascal: 'IconPlayArrowFill', kebab: 'icon-play-arrow-fill' },
  { pascal: 'IconPlayCircle', kebab: 'icon-play-circle' },
  { pascal: 'IconPlayCircleFill', kebab: 'icon-play-circle-fill' },
  { pascal: 'IconPlus', kebab: 'icon-plus' },
  { pascal: 'IconPlusCircle', kebab: 'icon-plus-circle' },
  { pascal: 'IconPlusCircleFill', kebab: 'icon-plus-circle-fill' },
  { pascal: 'IconPoweroff', kebab: 'icon-poweroff' },
  { pascal: 'IconPrinter', kebab: 'icon-printer' },
  { pascal: 'IconPublic', kebab: 'icon-public' },
  { pascal: 'IconPushpin', kebab: 'icon-pushpin' },
  { pascal: 'IconQq', kebab: 'icon-qq' },
  { pascal: 'IconQqCircleFill', kebab: 'icon-qq-circle-fill' },
  { pascal: 'IconQqZone', kebab: 'icon-qq-zone' },
  { pascal: 'IconQrcode', kebab: 'icon-qrcode' },
  { pascal: 'IconQuestion', kebab: 'icon-question' },
  { pascal: 'IconQuestionCircle', kebab: 'icon-question-circle' },
  { pascal: 'IconQuestionCircleFill', kebab: 'icon-question-circle-fill' },
  { pascal: 'IconQuote', kebab: 'icon-quote' },
  { pascal: 'IconRecord', kebab: 'icon-record' },
  { pascal: 'IconRecordStop', kebab: 'icon-record-stop' },
  { pascal: 'IconRedo', kebab: 'icon-redo' },
  { pascal: 'IconRefresh', kebab: 'icon-refresh' },
  { pascal: 'IconRelation', kebab: 'icon-relation' },
  { pascal: 'IconReply', kebab: 'icon-reply' },
  { pascal: 'IconRight', kebab: 'icon-right' },
  { pascal: 'IconRightCircle', kebab: 'icon-right-circle' },
  { pascal: 'IconRobot', kebab: 'icon-robot' },
  { pascal: 'IconRobotAdd', kebab: 'icon-robot-add' },
  { pascal: 'IconRotateLeft', kebab: 'icon-rotate-left' },
  { pascal: 'IconRotateRight', kebab: 'icon-rotate-right' },
  { pascal: 'IconSafe', kebab: 'icon-safe' },
  { pascal: 'IconSave', kebab: 'icon-save' },
  { pascal: 'IconScan', kebab: 'icon-scan' },
  { pascal: 'IconSchedule', kebab: 'icon-schedule' },
  { pascal: 'IconScissor', kebab: 'icon-scissor' },
  { pascal: 'IconSearch', kebab: 'icon-search' },
  { pascal: 'IconSelectAll', kebab: 'icon-select-all' },
  { pascal: 'IconSend', kebab: 'icon-send' },
  { pascal: 'IconSettings', kebab: 'icon-settings' },
  { pascal: 'IconShake', kebab: 'icon-shake' },
  { pascal: 'IconShareAlt', kebab: 'icon-share-alt' },
  { pascal: 'IconShareExternal', kebab: 'icon-share-external' },
  { pascal: 'IconShareInternal', kebab: 'icon-share-internal' },
  { pascal: 'IconShrink', kebab: 'icon-shrink' },
  { pascal: 'IconSkin', kebab: 'icon-skin' },
  { pascal: 'IconSkipNext', kebab: 'icon-skip-next' },
  { pascal: 'IconSkipNextFill', kebab: 'icon-skip-next-fill' },
  { pascal: 'IconSkipPrevious', kebab: 'icon-skip-previous' },
  { pascal: 'IconSkipPreviousFill', kebab: 'icon-skip-previous-fill' },
  { pascal: 'IconSort', kebab: 'icon-sort' },
  { pascal: 'IconSortAscending', kebab: 'icon-sort-ascending' },
  { pascal: 'IconSortDescending', kebab: 'icon-sort-descending' },
  { pascal: 'IconSound', kebab: 'icon-sound' },
  { pascal: 'IconSoundFill', kebab: 'icon-sound-fill' },
  { pascal: 'IconStamp', kebab: 'icon-stamp' },
  { pascal: 'IconStar', kebab: 'icon-star' },
  { pascal: 'IconStarFill', kebab: 'icon-star-fill' },
  { pascal: 'IconStop', kebab: 'icon-stop' },
  { pascal: 'IconStorage', kebab: 'icon-storage' },
  { pascal: 'IconStrikethrough', kebab: 'icon-strikethrough' },
  { pascal: 'IconSubscribe', kebab: 'icon-subscribe' },
  { pascal: 'IconSubscribeAdd', kebab: 'icon-subscribe-add' },
  { pascal: 'IconSubscribed', kebab: 'icon-subscribed' },
  { pascal: 'IconSun', kebab: 'icon-sun' },
  { pascal: 'IconSunFill', kebab: 'icon-sun-fill' },
  { pascal: 'IconSwap', kebab: 'icon-swap' },
  { pascal: 'IconSync', kebab: 'icon-sync' },
  { pascal: 'IconTag', kebab: 'icon-tag' },
  { pascal: 'IconTags', kebab: 'icon-tags' },
  { pascal: 'IconThumbDown', kebab: 'icon-thumb-down' },
  { pascal: 'IconThumbDownFill', kebab: 'icon-thumb-down-fill' },
  { pascal: 'IconThumbUp', kebab: 'icon-thumb-up' },
  { pascal: 'IconThumbUpFill', kebab: 'icon-thumb-up-fill' },
  { pascal: 'IconThunderbolt', kebab: 'icon-thunderbolt' },
  { pascal: 'IconTiktokColor', kebab: 'icon-tiktok-color' },
  { pascal: 'IconToBottom', kebab: 'icon-to-bottom' },
  { pascal: 'IconToLeft', kebab: 'icon-to-left' },
  { pascal: 'IconToRight', kebab: 'icon-to-right' },
  { pascal: 'IconToTop', kebab: 'icon-to-top' },
  { pascal: 'IconTool', kebab: 'icon-tool' },
  { pascal: 'IconTranslate', kebab: 'icon-translate' },
  { pascal: 'IconTrophy', kebab: 'icon-trophy' },
  { pascal: 'IconTwitter', kebab: 'icon-twitter' },
  { pascal: 'IconTwitterCircleFill', kebab: 'icon-twitter-circle-fill' },
  { pascal: 'IconUnderline', kebab: 'icon-underline' },
  { pascal: 'IconUndo', kebab: 'icon-undo' },
  { pascal: 'IconUnlock', kebab: 'icon-unlock' },
  { pascal: 'IconUnorderedList', kebab: 'icon-unordered-list' },
  { pascal: 'IconUp', kebab: 'icon-up' },
  { pascal: 'IconUpCircle', kebab: 'icon-up-circle' },
  { pascal: 'IconUpload', kebab: 'icon-upload' },
  { pascal: 'IconUser', kebab: 'icon-user' },
  { pascal: 'IconUserAdd', kebab: 'icon-user-add' },
  { pascal: 'IconUserGroup', kebab: 'icon-user-group' },
  { pascal: 'IconVideoCamera', kebab: 'icon-video-camera' },
  { pascal: 'IconVoice', kebab: 'icon-voice' },
  { pascal: 'IconWechat', kebab: 'icon-wechat' },
  { pascal: 'IconWechatpay', kebab: 'icon-wechatpay' },
  { pascal: 'IconWeibo', kebab: 'icon-weibo' },
  { pascal: 'IconWeiboCircleFill', kebab: 'icon-weibo-circle-fill' },
  { pascal: 'IconWifi', kebab: 'icon-wifi' },
  { pascal: 'IconWoman', kebab: 'icon-woman' },
  { pascal: 'IconXiguaColor', kebab: 'icon-xigua-color' },
  { pascal: 'IconZoomIn', kebab: 'icon-zoom-in' },
  { pascal: 'IconZoomOut', kebab: 'icon-zoom-out' },
];

/** 所有 PascalCase 图标名（便于渲染网格） */
export const arcoIconPascalNames: string[] = [
  'IconAlignCenter',
  'IconAlignLeft',
  'IconAlignRight',
  'IconAlipayCircle',
  'IconApps',
  'IconArchive',
  'IconArrowDown',
  'IconArrowFall',
  'IconArrowLeft',
  'IconArrowRight',
  'IconArrowRise',
  'IconArrowUp',
  'IconAt',
  'IconAttachment',
  'IconBackward',
  'IconBarChart',
  'IconBgColors',
  'IconBold',
  'IconBook',
  'IconBookmark',
  'IconBranch',
  'IconBrush',
  'IconBug',
  'IconBulb',
  'IconBytedanceColor',
  'IconCalendar',
  'IconCalendarClock',
  'IconCamera',
  'IconCaretDown',
  'IconCaretLeft',
  'IconCaretRight',
  'IconCaretUp',
  'IconCheck',
  'IconCheckCircle',
  'IconCheckCircleFill',
  'IconCheckSquare',
  'IconChineseFill',
  'IconClockCircle',
  'IconClose',
  'IconCloseCircle',
  'IconCloseCircleFill',
  'IconCloud',
  'IconCloudDownload',
  'IconCode',
  'IconCodeBlock',
  'IconCodeSandbox',
  'IconCodeSquare',
  'IconCodepen',
  'IconCommand',
  'IconCommon',
  'IconCompass',
  'IconComputer',
  'IconCopy',
  'IconCopyright',
  'IconCustomerService',
  'IconDashboard',
  'IconDelete',
  'IconDesktop',
  'IconDice',
  'IconDoubleDown',
  'IconDoubleLeft',
  'IconDoubleRight',
  'IconDoubleUp',
  'IconDown',
  'IconDownCircle',
  'IconDownload',
  'IconDragArrow',
  'IconDragDot',
  'IconDragDotVertical',
  'IconDriveFile',
  'IconEar',
  'IconEdit',
  'IconEmail',
  'IconEmpty',
  'IconEnglishFill',
  'IconEraser',
  'IconExclamation',
  'IconExclamationCircle',
  'IconExclamationCircleFill',
  'IconExclamationPolygonFill',
  'IconExpand',
  'IconExperiment',
  'IconExport',
  'IconEye',
  'IconEyeInvisible',
  'IconFaceBookCircleFill',
  'IconFaceFrownFill',
  'IconFaceMehFill',
  'IconFaceSmileFill',
  'IconFacebook',
  'IconFacebookSquareFill',
  'IconFile',
  'IconFileAudio',
  'IconFileImage',
  'IconFilePdf',
  'IconFileVideo',
  'IconFilter',
  'IconFindReplace',
  'IconFire',
  'IconFolder',
  'IconFolderAdd',
  'IconFolderDelete',
  'IconFontColors',
  'IconFormula',
  'IconForward',
  'IconFullscreen',
  'IconFullscreenExit',
  'IconGift',
  'IconGithub',
  'IconGitlab',
  'IconGoogle',
  'IconGoogleCircleFill',
  'IconH1',
  'IconH2',
  'IconH3',
  'IconH4',
  'IconH5',
  'IconH6',
  'IconH7',
  'IconHeart',
  'IconHeartFill',
  'IconHighlight',
  'IconHistory',
  'IconHome',
  'IconIdcard',
  'IconImage',
  'IconImageClose',
  'IconImport',
  'IconInfo',
  'IconInfoCircle',
  'IconInfoCircleFill',
  'IconInteraction',
  'IconItalic',
  'IconLanguage',
  'IconLarkColor',
  'IconLaunch',
  'IconLayers',
  'IconLayout',
  'IconLeft',
  'IconLeftCircle',
  'IconLineHeight',
  'IconLink',
  'IconList',
  'IconLiveBroadcast',
  'IconLoading',
  'IconLocation',
  'IconLock',
  'IconLoop',
  'IconMan',
  'IconMenu',
  'IconMenuFold',
  'IconMenuUnfold',
  'IconMessage',
  'IconMessageBanned',
  'IconMindMapping',
  'IconMinus',
  'IconMinusCircle',
  'IconMinusCircleFill',
  'IconMobile',
  'IconMoon',
  'IconMoonFill',
  'IconMore',
  'IconMoreVertical',
  'IconMosaic',
  'IconMusic',
  'IconMute',
  'IconMuteFill',
  'IconNav',
  'IconNotification',
  'IconNotificationClose',
  'IconObliqueLine',
  'IconOrderedList',
  'IconOriginalSize',
  'IconPalette',
  'IconPaste',
  'IconPause',
  'IconPauseCircle',
  'IconPauseCircleFill',
  'IconPen',
  'IconPenFill',
  'IconPhone',
  'IconPlayArrow',
  'IconPlayArrowFill',
  'IconPlayCircle',
  'IconPlayCircleFill',
  'IconPlus',
  'IconPlusCircle',
  'IconPlusCircleFill',
  'IconPoweroff',
  'IconPrinter',
  'IconPublic',
  'IconPushpin',
  'IconQq',
  'IconQqCircleFill',
  'IconQqZone',
  'IconQrcode',
  'IconQuestion',
  'IconQuestionCircle',
  'IconQuestionCircleFill',
  'IconQuote',
  'IconRecord',
  'IconRecordStop',
  'IconRedo',
  'IconRefresh',
  'IconRelation',
  'IconReply',
  'IconRight',
  'IconRightCircle',
  'IconRobot',
  'IconRobotAdd',
  'IconRotateLeft',
  'IconRotateRight',
  'IconSafe',
  'IconSave',
  'IconScan',
  'IconSchedule',
  'IconScissor',
  'IconSearch',
  'IconSelectAll',
  'IconSend',
  'IconSettings',
  'IconShake',
  'IconShareAlt',
  'IconShareExternal',
  'IconShareInternal',
  'IconShrink',
  'IconSkin',
  'IconSkipNext',
  'IconSkipNextFill',
  'IconSkipPrevious',
  'IconSkipPreviousFill',
  'IconSort',
  'IconSortAscending',
  'IconSortDescending',
  'IconSound',
  'IconSoundFill',
  'IconStamp',
  'IconStar',
  'IconStarFill',
  'IconStop',
  'IconStorage',
  'IconStrikethrough',
  'IconSubscribe',
  'IconSubscribeAdd',
  'IconSubscribed',
  'IconSun',
  'IconSunFill',
  'IconSwap',
  'IconSync',
  'IconTag',
  'IconTags',
  'IconThumbDown',
  'IconThumbDownFill',
  'IconThumbUp',
  'IconThumbUpFill',
  'IconThunderbolt',
  'IconTiktokColor',
  'IconToBottom',
  'IconToLeft',
  'IconToRight',
  'IconToTop',
  'IconTool',
  'IconTranslate',
  'IconTrophy',
  'IconTwitter',
  'IconTwitterCircleFill',
  'IconUnderline',
  'IconUndo',
  'IconUnlock',
  'IconUnorderedList',
  'IconUp',
  'IconUpCircle',
  'IconUpload',
  'IconUser',
  'IconUserAdd',
  'IconUserGroup',
  'IconVideoCamera',
  'IconVoice',
  'IconWechat',
  'IconWechatpay',
  'IconWeibo',
  'IconWeiboCircleFill',
  'IconWifi',
  'IconWoman',
  'IconXiguaColor',
  'IconZoomIn',
  'IconZoomOut',
];
